title: COEN 281: Winter 2023
description: Introduction to Data Mining & Pattern Recognition
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
