title: COEN 281 Winter 2023
description: Introduction to Data Mining & Pattern Recognition
theme: just-the-docs

url: https://coen2812023.github.io/

aux_links:
  Canvas: https://github.com/just-the-docs/just-the-docs-template
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
